import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./Providers";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDB Clone",
  description: "IMDB Clone Generated by Harsh-Kumar",
};

import React from "react";

const layout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* Header */}
          <Header />

          {/* Navbar */}
          <NavBar />
          {/* Search */}

          {children}
        </Providers>
      </body>
    </html>
  );
};

export default layout;
